require 'buildr/scala'

GLL = task '../target/classes' do
  Dir.chdir '..' do
    system 'buildr compile' or fail 'Failed to compile gll-combinators.'
  end
end

define 'examples' do
  compile.with GLL
  
  run_eg = proc do |name|
    classname = "#{name.downcase}.#{name}Parser"
    
    puts "Running #{name} example"
    puts
    
    cp = compile.dependencies.map(&:to_s).join(File::PATH_SEPARATOR) + File::PATH_SEPARATOR + _(:target, :classes)
    trace cp
    system 'java', '-cp', cp, classname, *Dir.glob("input/#{name.downcase}/*")
  end
  
  task :arithmetic => :compile do
    run_eg.call 'Arithmetic'
  end
  
  task :miniml => :compile do
    run_eg.call 'MiniML'
  end
  
  task :run => [:arithmetic, :miniml]
end
